package multithreading;

public class ThreadDemo {
	public static void main(String[] args) { // main thread
		MyThread t = new MyThread();
		t.start();
		//2 threads
		for(int i=0; i<10; i++) {
			System.out.println(Thread.currentThread().getName() +"main thread");
		} // by main
//Thread.currentThread().setPriority(0);

	}
}

MULTITHREADING


//MULTITASKING TYPES:
//
//PROCESS BASED -> each task is independent processes..no dependency 
//typing, listening , downloading
//
//THREAD BASED 
//programming best 
//
//performance inc
//timing reduced 
//
//Thread defining:
//
//thread -> separate flow of execution .
//   for every thread, job is there 
//1. by extending thread class
//2. implementing runnable interface 
//Thread scheduler
// part of jvm, responsible to schedule threads


//start()  heart of multithrading
//1. Register thread with thread scheduler
//2. perform mandatory activities req for thread.
//3. invoke run() 

//run
//overload ok, but no use
// start overrided, but no use  normal

//currentThread().getName(), set name 


//Thread priority 1- 10
//default: 5
//max :10
//min:1
//every thread has priority 
//  either generated by JVM
//  customized priority by programmer
//getpriority, set priority